name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit_tests:
    name: bats unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Install bats
        run: sudo npm install -g bats
      - name: Run unit tests
        run: bats test/

  plugin_test:
    name: asdf plugin okta-aws-cli test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@a7acd3c0f80eb138922a2da9514d1df22864eaca # v4
        with:
          command: okta-aws-cli --version
